COLUMN_MAPPING = {
    "RA": "ra",
    "Fase": "phase",
    "Turma": "class",
    "Nome": "name",
    "Nome Anonimizado": "anonymized_name",
    "Ano nasc": "birth_year",
    "Data de Nasc": "birth_date",
    "Idade 22": "age_22",
    "Gênero": "gender",
    "Ano ingresso": "admission_year",
    "Instituição de ensino": "education_institution",
    "Escola": "school",
    "Pedra 20": "stone_20",
    "Pedra 21": "stone_21",
    "Pedra 22": "stone_22",
    "Pedra 23": "stone_23",
    "Pedra 2023": "stone_2023",
    "Pedra 2024": "stone_2024",
    "INDE 22": "inde_22",
    "INDE 23": "inde_23",
    "INDE 2023": "inde_2023",
    "INDE 2024": "inde_2024",
    "IPP": "ipp",
    "Cg": "cg",
    "Cf": "cf",
    "Ct": "ct",
    "Nº Av": "num_av",
    "Avaliador1": "evaluator_1",
    "Rec Av1": "evaluator_1_feedback",
    "Avaliador2": "evaluator_2",
    "Rec Av2": "evaluator_2_feedback",
    "Avaliador3": "evaluator_3",
    "Rec Av3": "evaluator_3_feedback",
    "Avaliador4": "evaluator_4",
    "Rec Av4": "evaluator_4_feedback",
    "Avaliador5": "evaluator_5",
    "Avaliador6": "evaluator_6",
    "IAA": "iaa",
    "IEG": "ieg",
    "IPS": "ips",
    "Rec Psicologia": "psychology_feedback",
    "IDA": "ida",
    "Mat": "math",
    "Matem": "math",
    "Por": "portuguese",
    "Portug": "portuguese",
    "Ing": "english",
    "Inglês": "english",
    "Indicado": "indicated",
    "Atingiu PV": "reached_cutoff",
    "IPV": "ipv",
    "IAN": "ian",
    "Fase ideal": "ideal_phase",
    "Fase Ideal": "ideal_phase",
    "Defas": "lag",
    "Defasagem": "lag",
    "Destaque IEG": "ieg_highlight",
    "Destaque IDA": "ida_highlight",
    "Destaque IPV": "ipv_highlight",
    "Destaque IPV_1": "ipv_highlight_1",
    "Ativo/ Inativo": "active_inactive",
    "Ativo/ Inativo_1": "active_inactive_1",
}
