COLUMN_MAPPING = {
    "RA": "ra",
    "Fase": "phase",
    "Turma": "class",
    "Nome": "name",
    "Ano nasc": "birth_year",
    "Idade 22": "age_22",
    "Gênero": "gender",
    "Ano ingresso": "admission_year",
    "Instituição de ensino": "education_institution",
    "Pedra 20": "stone_20",
    "Pedra 21": "stone_21",
    "Pedra 22": "stone_22",
    "INDE 22": "inde_22",
    "Cg": "cg",
    "Cf": "cf",
    "Ct": "ct",
    "Nº Av": "num_av",
    "Avaliador1": "evaluator_1",
    "Rec Av1": "evaluator_1_feedback",
    "Avaliador2": "evaluator_2",
    "Rec Av2": "evaluator_2_feedback",
    "Avaliador3": "evaluator_3",
    "Rec Av3": "evaluator_3_feedback",
    "Avaliador4": "evaluator_4",
    "Rec Av4": "evaluator_4_feedback",
    "IAA": "iaa",
    "IEG": "ieg",
    "IPS": "ips",
    "Rec Psicologia": "psychology_feedback",
    "IDA": "ida",
    "Matem": "math",
    "Portug": "portuguese",
    "Inglês": "english",
    "Indicado": "indicated",
    "Atingiu PV": "reached_cutoff",
    "IPV": "ipv",
    "IAN": "ian",
    "Fase ideal": "ideal_phase",
    "Defas": "lag",
    "Destaque IEG": "ieg_highlight",
    "Destaque IDA": "ida_highlight",
    "Destaque IPV": "ipv_highlight",
}
